### ISSUE TITLE
Working only for page refresh

### ISSUE THREAD

**Issue by AndreaColombo-sesamo** [LayerXcom/next-navigation-guard#1]
Hi! 
I tried to use your library which i think could be very helpfull since something like this is not implemented in NEXT app router. 

I tried to wrap my content in a NavigationGuardProvider but it seems like it works only for page reloading and not if i navigate to another page through a Link element.

I'm doing something wrong or the library is tied only for the refreshing/reloading of the page? Thanks :>

Reference to the code i used: 

My wrapper:
```tsx
<NavigationGuardProvider>
      <Style />
</NavigationGuardProvider>
```

In the Style Component:
```tsx
  useNavigationGuard({
    enabled: true,
    confirm: () => window.confirm("You have unsaved changes that will be lost."),
  });
```

**Comment by jrnxf** [comment]
I have what seems to be the opposite issue. When I click around on links it works as expected, but if I hit the browser back button, the url changes but the route stays the same

**Comment by ypresto** [comment]
If you really wraps Style component only, you should wrap your whole application component instead. In app/layout.tsx, it looks like this:

```
<NavigationGuardProvider>
  {children}
</NavigationGuardProvider>
```

See example here:

https://github.com/LayerXcom/next-navigation-guard/blob/0d004a9ba598ad3ced17739da3b4b0a239a007c5/example/src/app/layout.tsx#L30

**Comment by ypresto** [comment]
@jrnxf Could you open new issue and provide version number of Next.js and the browser please? 🙇

**Comment by jrnxf** [comment]
> @jrnxf Could you open new issue and provide version number of Next.js and the browser please? 🙇

of course!

**Comment by AndreaColombo-sesamo** [comment]
My use case was to wrap only a page because i needed a custom logic for handling not saved input fields. 

The Style component i provided is returned from a Page.tsx file so i need to wrap only that. I think my usecase is a little bit tricky to handle 😅.

**Comment by ypresto** [comment]
> i needed a custom logic for handling not saved input fields.

Could you describe it more? 👀

You can write custom logic in enabled func:

```js
useNavigationGuard({  enabled: () => form.isChanged(), confirm: () => ... )
```

Note that generally custom logic should be placed to `enabled` not `confirm`, because only `enabled` will be called when user closes the tab.

**Comment by ypresto** [comment]
> i needed a custom logic for handling not saved input fields.

Could you describe it more? 👀

You can write custom logic in `enabled` func of `useNavigationGuard()` hook. So only one NavigationGuardProvider in root layout or _app.tsx is necessary for customizing.

```js
useNavigationGuard({ enabled: () => form.isChanged(), confirm: () => ... })
```

Note that generally custom logic should be placed to `enabled` not `confirm`, because only `enabled` will be called when user closes the tab.

**Comment by AndreaColombo-sesamo** [comment]
Thanks! I'll try it as soon as i can 😁

**Comment by nightwalker89** [comment]
all the best. it works for me. Refined + Nextjs 14 App Router +  Antd Form
