### ISSUE TITLE
browser back/forward buttons not working

### ISSUE THREAD

**Issue by jrnxf** [LayerXcom/next-navigation-guard#2]
I'm running the example straight from `/examples` and on every browser, when I hit the back / forward browser buttons, the URL changes but the page does not change.

I tried modifying the versions of next (even tried canary) and it's the same in every version. If I remove the `NavigationGuardProvider` and its corresponding hooks from the example the browser back/forward buttons work as expected.

You can see in this screenshot that after I hit the browser back button the URL is page2, but the page shows page 3

<img width="547" alt="image" src="https://github.com/user-attachments/assets/c6a008be-5cf5-48c0-bfe7-589dc2442113">

**Comment by ypresto** [comment]
This is just a bug 🙏  I'll deploy a fix soon!

**Comment by ypresto** [comment]
Fixed and released v0.1.1 ! Thank you for reporting!
