### ISSUE TITLE
Is there an option to change  a message that appears on reftresh? "confirm" value only replaces message for "back" or "link" navigation. 

### ISSUE THREAD

**Issue by PaulStat** [LayerXcom/next-navigation-guard#3]

**Comment by ypresto** [comment]
This is a limitation of browsers. We cannot not change the message on refresh or tab close. 😢 

https://developer.mozilla.org/en-US/docs/Web/API/Window/beforeunload_event#usage_notes

> Only show a generic browser-specified string in the displayed dialog. This cannot be controlled by the webpage code.
