### ISSUE TITLE
Peer dependency for Next 15

### ISSUE THREAD

**Issue by neoromantic** [LayerXcom/next-navigation-guard#5]
It seems to be working OK with next.15, but I get peer dependency warning. 

Could be fixed?

**Comment by ypresto** [comment]
Thanks for reminding! I'll fix it in next week!

**Comment by iypavlov** [comment]
relevant to me

**Comment by SimCall** [comment]
+

**Comment by zachelrath** [comment]
@ypresto Any updates on this? Happy to submit a PR if that is helpful, but seems like it should be a pretty small change.

**Comment by ypresto** [comment]
Published v0.1.2 🎉  Thank you for contribution! @zachelrath
